const names = [
  { 'name': 'Jesus' },
  { 'name': 'Napoleon' },
  { 'name': 'Muhammad' },
  { 'name': 'William Shakespeare' },
  { 'name': 'Abraham Lincoln' },
  { 'name': 'George Washington' },
  { 'name': 'Adolf Hitler' },
  { 'name': 'Aristotle' },
  { 'name': 'Alexander the Great' },
  { 'name': 'Thomas Jefferson' },
  { 'name': 'Henry VIII of England' },
  { 'name': 'Charles Darwin' },
  { 'name': 'Elizabeth I of England' },
  { 'name': 'Karl Marx' },
  { 'name': 'Julius Caesar' },
  { 'name': 'Queen Victoria' },
  { 'name': 'Martin Luther' },
  { 'name': 'Joseph Stalin' },
  { 'name': 'Albert Einstein' },
  { 'name': 'Christopher Columbus' },
  { 'name': 'Isaac Newton' },
  { 'name': 'Charlemagne' },
  { 'name': 'Theodore Roosevelt' },
  { 'name': 'Wolfgang Amadeus Mozart' },
  { 'name': 'Plato' },
  { 'name': 'Louis XIV of France' },
  { 'name': 'Ludwig van Beethoven' },
  { 'name': 'Ulysses S. Grant' },
  { 'name': 'Leonardo da Vinci' },
  { 'name': 'Augustus' },
  { 'name': 'Carl Linnaeus' },
  { 'name': 'Ronald Reagan' },
  { 'name': 'Charles Dickens' },
  { 'name': 'Paul the Apostle' },
  { 'name': 'Benjamin Franklin' },
  { 'name': 'George W. Bush' },
  { 'name': 'Winston Churchill' },
  { 'name': 'Genghis Khan' },
  { 'name': 'Charles I of England' },
  { 'name': 'Thomas Edison' },
  { 'name': 'James I of England' },
  { 'name': 'Friedrich Nietzsche' },
  { 'name': 'Franklin D. Roosevelt' },
  { 'name': 'Sigmund Freud' },
  { 'name': 'Alexander Hamilton' },
  { 'name': 'Mohandas Karamchand Gandhi' },
  { 'name': 'Woodrow Wilson' },
  { 'name': 'Johann Sebastian Bach' },
  { 'name': 'Galileo Galilei' },
  { 'name': 'Oliver Cromwell' },
  { 'name': 'James Madison' },
  { 'name': 'Gautama Buddha' },
  { 'name': 'Mark Twain' },
  { 'name': 'Edgar Allan Poe' },
  { 'name': 'Joseph Smith, Jr.' },
  { 'name': 'Adam Smith' },
  { 'name': 'David, King of Israel' },
  { 'name': 'George III of the United Kingdom' },
  { 'name': 'Immanuel Kant' },
  { 'name': 'James Cook' },
  { 'name': 'John Adams' },
  { 'name': 'Richard Wagner' },
  { 'name': 'Pyotr Ilyich Tchaikovsky' },
  { 'name': 'Voltaire' },
  { 'name': 'Saint Peter' },
  { 'name': 'Andrew Jackson' },
  { 'name': 'Constantine the Great' },
  { 'name': 'Socrates' },
  { 'name': 'Elvis Presley' },
  { 'name': 'William the Conqueror' },
  { 'name': 'John F. Kennedy' },
  { 'name': 'Augustine of Hippo' },
  { 'name': 'Vincent van Gogh' },
  { 'name': 'Nicolaus Copernicus' },
  { 'name': 'Vladimir Lenin' },
  { 'name': 'Robert E. Lee' },
  { 'name': 'Oscar Wilde' },
  { 'name': 'Charles II of England' },
  { 'name': 'Cicero' },
  { 'name': 'Jean-Jacques Rousseau' },
  { 'name': 'Francis Bacon' },
  { 'name': 'Richard Nixon' },
  { 'name': 'Louis XVI of France' },
  { 'name': 'Charles V, Holy Roman Emperor' },
  { 'name': 'King Arthur' },
  { 'name': 'Michelangelo' },
  { 'name': 'Philip II of Spain' },
  { 'name': 'Johann Wolfgang von Goethe' },
  { 'name': 'Ali, founder of Sufism' },
  { 'name': 'Thomas Aquinas' },
  { 'name': 'Pope John Paul II' },
  { 'name': 'René Descartes' },
  { 'name': 'Nikola Tesla' },
  { 'name': 'Harry S. Truman' },
  { 'name': 'Joan of Arc' },
  { 'name': 'Dante Alighieri' },
  { 'name': 'Otto von Bismarck' },
  { 'name': 'Grover Cleveland' },
  { 'name': 'John Calvin' },
  { 'name': 'John Locke' }
];

export default function giveMeName() {
  return names[Date.now() % 100]
}